[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "probe-rs run --no-location --chip STM32U031R8Tx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[profile.dev]
opt-level = "s"

[profile.release]
debug = 2

[env]
DEFMT_LOG = "info"
